export const FAMOUS_INDIAN_COLLEGES = [
  // IITs (Indian Institutes of Technology)
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Varanasi (BHU)",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",

  // IIMs (Indian Institutes of Management)
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Shillong",
  "Indian Institute of Management (IIM) Rohtak",
  "Indian Institute of Management (IIM) Raipur",
  "Indian Institute of Management (IIM) Ranchi",
  "Indian Institute of Management (IIM) Trichy",
  "Indian Institute of Management (IIM) Udaipur",
  "Indian Institute of Management (IIM) Kashipur",
  "Indian Institute of Management (IIM) Amritsar",
  "Indian Institute of Management (IIM) Bodh Gaya",
  "Indian Institute of Management (IIM) Nagpur",
  "Indian Institute of Management (IIM) Visakhapatnam",
  "Indian Institute of Management (IIM) Sirmaur",
  "Indian Institute of Management (IIM) Sambalpur",
  "Indian Institute of Management (IIM) Jammu",

  // NITs (National Institutes of Technology)
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Surathkal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Jaipur",
  "National Institute of Technology (NIT) Nagpur",
  "National Institute of Technology (NIT) Allahabad",
  "National Institute of Technology (NIT) Bhopal",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Arunachal Pradesh",
  "National Institute of Technology (NIT) Delhi",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Manipur",
  "National Institute of Technology (NIT) Meghalaya",
  "National Institute of Technology (NIT) Mizoram",
  "National Institute of Technology (NIT) Nagaland",
  "National Institute of Technology (NIT) Puducherry",
  "National Institute of Technology (NIT) Sikkim",
  "National Institute of Technology (NIT) Uttarakhand",
  "National Institute of Technology (NIT) Andhra Pradesh",
  "National Institute of Technology (NIT) Karnataka",
  "National Institute of Technology (NIT) Srinagar",

  // IISERs (Indian Institutes of Science Education and Research)
  "Indian Institute of Science Education and Research (IISER) Pune",
  "Indian Institute of Science Education and Research (IISER) Kolkata",
  "Indian Institute of Science Education and Research (IISER) Mohali",
  "Indian Institute of Science Education and Research (IISER) Bhopal",
  "Indian Institute of Science Education and Research (IISER) Thiruvananthapuram",
  "Indian Institute of Science Education and Research (IISER) Tirupati",
  "Indian Institute of Science Education and Research (IISER) Berhampur",

  // IISc and Other Premier Science Institutes
  "Indian Institute of Science (IISc) Bangalore",
  "Indian Statistical Institute (ISI) Kolkata",
  "Indian Statistical Institute (ISI) Delhi",
  "Indian Statistical Institute (ISI) Bangalore",
  "Tata Institute of Fundamental Research (TIFR) Mumbai",

  // Medical Colleges - AIIMS
  "All India Institute of Medical Sciences (AIIMS) New Delhi",
  "All India Institute of Medical Sciences (AIIMS) Bhopal",
  "All India Institute of Medical Sciences (AIIMS) Bhubaneswar",
  "All India Institute of Medical Sciences (AIIMS) Jodhpur",
  "All India Institute of Medical Sciences (AIIMS) Patna",
  "All India Institute of Medical Sciences (AIIMS) Raipur",
  "All India Institute of Medical Sciences (AIIMS) Rishikesh",
  "All India Institute of Medical Sciences (AIIMS) Nagpur",
  "All India Institute of Medical Sciences (AIIMS) Mangalagiri",
  "All India Institute of Medical Sciences (AIIMS) Gorakhpur",
  "All India Institute of Medical Sciences (AIIMS) Jammu",
  "All India Institute of Medical Sciences (AIIMS) Kalyani",
  "All India Institute of Medical Sciences (AIIMS) Deoghar",
  "All India Institute of Medical Sciences (AIIMS) Bibinagar",
  "All India Institute of Medical Sciences (AIIMS) Bathinda",

  // Other Premier Medical Colleges
  "Christian Medical College (CMC) Vellore",
  "Armed Forces Medical College (AFMC) Pune",
  "Maulana Azad Medical College (MAMC) Delhi",
  "King George's Medical University (KGMU) Lucknow",
  "Postgraduate Institute of Medical Education and Research (PGIMER) Chandigarh",
  "Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGIMS) Lucknow",
  "Kasturba Medical College (KMC) Manipal",
  "St. John's Medical College Bangalore",
  "Government Medical College Thiruvananthapuram",
  "Grant Medical College Mumbai",

  // Central Universities
  "Jawaharlal Nehru University (JNU) Delhi",
  "University of Delhi (DU)",
  "Banaras Hindu University (BHU) Varanasi",
  "Aligarh Muslim University (AMU) Aligarh",
  "Jamia Millia Islamia (JMI) Delhi",
  "Hyderabad Central University",
  "Pondicherry University",
  "Tezpur University",
  "North Eastern Hill University (NEHU) Shillong",
  "Manipur University",
  "Mizoram University",
  "Nagaland University",
  "Tripura University",
  "Assam University",
  "Sikkim University",

  // State Universities & Deemed Universities
  "Anna University Chennai",
  "University of Mumbai",
  "University of Calcutta",
  "University of Madras",
  "Pune University (SPPU)",
  "Gujarat University",
  "Rajasthan University",
  "Punjab University Chandigarh",
  "Kurukshetra University",
  "Panjab University Chandigarh",
  "Guru Nanak Dev University Amritsar",
  "Jadavpur University Kolkata",
  "Presidency University Kolkata",
  "Calcutta University",
  "Osmania University Hyderabad",
  "Andhra University Visakhapatnam",
  "University of Kerala",
  "Mahatma Gandhi University Kerala",
  "Cochin University of Science and Technology (CUSAT)",
  "Karnataka University Dharwad",
  "Bangalore University",
  "Mysore University",
  "Visvesvaraya Technological University (VTU) Karnataka",

  // Engineering Colleges
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT) Delhi",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "BITS Pilani Goa Campus",
  "BITS Pilani Hyderabad Campus",
  "Vellore Institute of Technology (VIT) Vellore",
  "VIT Bhopal",
  "VIT Chennai",
  "VIT-AP Amaravati",
  "SRM Institute of Science and Technology Chennai",
  "Manipal Institute of Technology (MIT) Manipal",
  "PES University Bangalore",
  "R.V. College of Engineering Bangalore",
  "BMS College of Engineering Bangalore",
  "MS Ramaiah Institute of Technology Bangalore",
  "Dayananda Sagar College of Engineering Bangalore",
  "JSS Science and Technology University Mysore",
  "Amrita Vishwa Vidyapeetham Coimbatore",
  "Amrita School of Engineering Bangalore",
  "Amrita School of Engineering Kochi",
  "Lovely Professional University (LPU) Punjab",
  "Thapar Institute of Engineering and Technology Patiala",
  "Punjab Engineering College (PEC) Chandigarh",
  "Chitkara University Punjab",
  "Bennett University Greater Noida",
  "Shiv Nadar University Greater Noida",
  "Jaypee Institute of Information Technology (JIIT) Noida",
  "Amity University Noida",
  "Galgotias University Greater Noida",
  "KIET Group of Institutions Ghazigarh",
  "JSS Academy of Technical Education Noida",
  "ABES Engineering College Ghaziabad",
  "AKGEC Ghaziabad",
  "IMS Engineering College Ghaziabad",
  "GL Bajaj Institute of Technology and Management Greater Noida",
  "Bharati Vidyapeeth Deemed University Pune",
  "College of Engineering Pune (COEP)",
  "Vishwakarma Institute of Technology (VIT) Pune",
  "MIT Academy of Engineering Pune",
  "Sinhgad College of Engineering Pune",
  "Symbiosis Institute of Technology (SIT) Pune",
  "International Institute of Information Technology (IIIT) Hyderabad",
  "International Institute of Information Technology (IIIT) Bangalore",
  "International Institute of Information Technology (IIIT) Delhi",
  "International Institute of Information Technology (IIIT) Allahabad",
  "Indian Institute of Information Technology (IIIT) Lucknow",
  "Indian Institute of Information Technology (IIIT) Guwahati",
  "Indian Institute of Information Technology (IIIT) Jabalpur",
  "Indian Institute of Information Technology (IIIT) Kancheepuram",
  "Indian Institute of Information Technology (IIIT) Kota",
  "Indian Institute of Information Technology (IIIT) Pune",
  "Indian Institute of Information Technology (IIIT) Vadodara",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT) Gandhinagar",
  "Nirma University Ahmedabad",
  "Institute of Chemical Technology (ICT) Mumbai",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat",
  "Pandit Deendayal Energy University (PDEU) Gandhinagar",
  "Kalinga Institute of Industrial Technology (KIIT) Bhubaneswar",
  "Institute of Technical Education and Research (ITER) Bhubaneswar",
  "CV Raman Global University Bhubaneswar",
  "Siksha 'O' Anusandhan University Bhubaneswar",
  "Centurion University Bhubaneswar",

  // Architecture and Design Colleges
  "Indian Institute of Technology (IIT) Kharagpur - Architecture",
  "School of Planning and Architecture (SPA) Delhi",
  "School of Planning and Architecture (SPA) Bhopal",
  "School of Planning and Architecture (SPA) Vijayawada",
  "National Institute of Design (NID) Ahmedabad",
  "National Institute of Fashion Technology (NIFT) Delhi",
  "Pearl Academy Delhi",
  "Sushant School of Art and Architecture",

  // Law Colleges
  "National Law School of India University (NLSIU) Bangalore",
  "National Academy of Legal Studies and Research (NALSAR) Hyderabad",
  "West Bengal National University of Juridical Sciences (WBNUJS) Kolkata",
  "National Law University (NLU) Jodhpur",
  "Gujarat National Law University (GNLU) Gandhinagar",
  "Rajiv Gandhi School of Intellectual Property Law (RGSIPLR) Kharagpur",
  "The Tamil Nadu Dr. Ambedkar Law University Chennai",
  "Faculty of Law University of Delhi",
  "Jamia Millia Islamia Faculty of Law Delhi",

  // Management and Business Schools
  "Indian School of Business (ISB) Hyderabad",
  "Indian School of Business (ISB) Mohali",
  "XLRI Xavier School of Management Jamshedpur",
  "SP Jain Institute of Management and Research (SPJIMR) Mumbai",
  "Narsee Monjee Institute of Management Studies (NMIMS) Mumbai",
  "Symbiosis Institute of Business Management (SIBM) Pune",
  "Indian Institute of Management Technology (IIMT) Ghaziabad",
  "Management Development Institute (MDI) Gurgaon",
  "Faculty of Management Studies (FMS) University of Delhi",
  "Indian Institute of Foreign Trade (IIFT) Delhi",
  "International Management Institute (IMI) Delhi",
  "T.A. Pai Management Institute (TAPMI) Manipal",
  "Institute of Management Technology (IMT) Ghaziabad",
  "Great Lakes Institute of Management Chennai",
  "K.J. Somaiya Institute of Management Studies and Research Mumbai",
  "Prin. L.N. Welingkar Institute of Management Development and Research Mumbai",

  // Journalism and Mass Communication
  "Indian Institute of Mass Communication (IIMC) Delhi",
  "Asian College of Journalism (ACJ) Chennai",
  "Symbiosis Institute of Media and Communication (SIMC) Pune",
  "Xavier Institute of Communications (XIC) Mumbai",
  "Mudra Institute of Communications Ahmedabad (MICA)",

  // Hotel Management
  "Institute of Hotel Management (IHM) Delhi",
  "Institute of Hotel Management (IHM) Mumbai",
  "Institute of Hotel Management (IHM) Chennai",
  "Institute of Hotel Management (IHM) Bangalore",
  "Institute of Hotel Management (IHM) Kolkata",
  "Welcomgroup Graduate School of Hotel Administration Manipal",

  // Fashion and Design
  "National Institute of Fashion Technology (NIFT) Delhi",
  "National Institute of Fashion Technology (NIFT) Mumbai",
  "National Institute of Fashion Technology (NIFT) Bangalore",
  "National Institute of Fashion Technology (NIFT) Chennai",
  "National Institute of Fashion Technology (NIFT) Kolkata",
  "Pearl Academy Mumbai",
  "Pearl Academy Jaipur",
  "Raffles Design International Mumbai",

  // Agriculture Universities
  "Indian Agricultural Research Institute (IARI) Delhi",
  "Punjab Agricultural University (PAU) Ludhiana",
  "Tamil Nadu Agricultural University (TNAU) Coimbatore",
  "University of Agricultural Sciences (UAS) Bangalore",
  "Chaudhary Charan Singh Haryana Agricultural University Hisar",
  "Govind Ballabh Pant University of Agriculture and Technology Pantnagar",
  "Acharya N.G. Ranga Agricultural University Hyderabad",

  // Veterinary Colleges
  "Indian Veterinary Research Institute (IVRI) Bareilly",
  "Madras Veterinary College Chennai",
  "College of Veterinary Science Tirupati",
  "Bombay Veterinary College Mumbai",

  // Pharmacy Colleges
  "Jamia Hamdard University Delhi",
  "Institute of Chemical Technology (ICT) Mumbai",
  "National Institute of Pharmaceutical Education and Research (NIPER) Mohali",
  "Manipal College of Pharmaceutical Sciences",
  "JSS College of Pharmacy Mysore",

  // Others
  "Tata Institute of Social Sciences (TISS) Mumbai",
  "Indian Institute of Science (IISc) Bangalore",
  "Homi Bhabha National Institute Mumbai",
  "Institute for Plasma Research Gandhinagar",
  "Variable Energy Cyclotron Centre Kolkata",
  "Saha Institute of Nuclear Physics Kolkata",
  "Institute of Mathematical Sciences Chennai"
];

// Function to search colleges based on input
export const searchColleges = (query: string): string[] => {
  if (!query || query.length < 2) return [];

  const lowercaseQuery = query.toLowerCase();

  return FAMOUS_INDIAN_COLLEGES.filter(college =>
    college.toLowerCase().includes(lowercaseQuery)
  ).slice(0, 10); // Limit to 10 suggestions
};

// Function to get all colleges (for reference)
export const getAllColleges = (): string[] => {
  return FAMOUS_INDIAN_COLLEGES.sort();
};